# Generated by Django 5.1.4 on 2024-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
